version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.12.24

jobs:
  check:
    executor: terraform
    steps:
      - checkout
      - run:
          name: lint
          command: make lint
  integration-test:
    executor: terraform
    steps:
      - run: apk add --update --no-cache make ca-certificates openssh-keygen openssh-client bash python
      - run: wget https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl -O /opt/bin/kubectl && chmod +x /opt/bin/kubectl
      - checkout
      - add_ssh_keys
      - run: ssh-add $HOME/.ssh/id_rsa
      - run:
          name: integration test
          command: make test
      - run:
          name: failure cleanup
          command: make destroy
          when: on_fail

workflows:
  version: 2
  main:
    jobs:
      - check
      - integration-test:
          filters:
            branches:
              only:
                - master
