version: 2.1

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:0.12.24

commands:
  install_build_deps:
    description: install all builds deps
    steps:
      - run: apk add --update --no-cache make ca-certificates openssh-keygen openssh-client bash python

jobs:
  check:
    executor: terraform
    steps:
      - install_build_deps
      - checkout
      - run:
          name: lint
          command: make lint
  integration-test:
    executor: terraform
    steps:
      - install_build_deps
      - checkout
      - run: ssh-keygen -b 4096 -t rsa -f $HOME/.ssh/id_rsa -q -N ""
      - run: wget https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl
      - run: ssh-add $HOME/.ssh/id_rsa
      - run:
          name: integration test
          command: make test
      - run:
          name: failure cleanup
          command: make destroy
          when: on_fail

workflows:
  version: 2
  main:
    jobs:
      - check
      - integration-test:
          filters:
            branches:
              only: master
